[package]
name = "heavens"
version = "0.2.0"
edition = "2021"
authors = ["Freddy Wordingham <freddy@digilab.co.uk>"]
description = "N-body simulation of a star cluster using Rust + GPU"
license = "MIT"

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
image = "0.24.6"
json5 = "0.4.1"
nalgebra = "0.32.2"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
ocl = "0.19.4"
palette = "0.6.1"
rand = "0.8.5"
serde = { version = "1.0.*", features = ["derive"] }
